# dependencies for patchprobe package
#
# To use:
#   conda env create -f environment.yml
# and then
#   conda activate patchprobe
#
# To update dependencies after changing this environment file:
#   conda env update --name patchprobe --file environment.yml --prune
#
# can also use mamba instead of conda in the above
name: patchprobe
channels:
  - conda-forge
dependencies:
  - numpy=1.23.3
  - pandas=1.5.0
  - xarray=2022.9.0
  - pymc=4.2.1
  - aesara=2.8.6
  - arviz=0.12.1
  - matplotlib=3.4.3
  - seaborn=0.12.0
  - proplot=0.9.5

  # include jupyterlab for convenience
  - jupyterlab
