"""
This module contains utility routines.

Part of the patchprobe package.

Copyright 2022, 2023, 2025 Vinothan N. Manoharan <vnm@seas.harvard.edu>

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.
"""

import xarray as xr

def dataset_from_summary(summary):
    """
    Utility function to reconstruct the original dataset that was used in an
    inference calculation.  All the information for the dataset is stored in
    the summary statistics saved by pp.PatchprobeModel.sample().

    Parameters
    ----------
    summary : xarray Dataset
        Summary statistics generated by pp.PatchprobeModel.sample().  Should
        include the analyzed data (as variables) and metadata (as attributes).
    """

    dataset = xr.Dataset({'background': summary.background,
                          'patchprobe': summary.patchprobe})
    if 'errors' in summary:
        dataset['errors'] = summary.errors

    # copy all the metadata; this will copy a lot of metadata from the
    # sampling (such as the arviz version and model type) but all the dataset
    # metadata will be there, and we don't have to update this function if the
    # metadata changes.
    dataset.attrs = summary.attrs.copy()

    return dataset
